chore(migrations): more robust migration of possibly missing plugin tables (#7355)
### Summary

An old EE migration tried to migrate following:
```
        "keyauth_credentials",
        "oauth2_tokens",
        "oauth2_authorization_codes",
```

But it is always possible to run Kong without key-auth and oauth2 plugins,
and I hit just that problem myself. This leads to:

```
Error: [PostgreSQL error] cluster_mutex callback threw an error: ./kong/cmd/utils/migrations.lua:174: [PostgreSQL error] failed to run migration '006_1301_to_1500' teardown: ...se_edition/db/migrations/enterprise/006_1301_to_1500.lua:183: ERROR: relation "keyauth_credentials" does not exist (189)
stack traceback:
	[C]: in function 'assert'
	...se_edition/db/migrations/enterprise/006_1301_to_1500.lua:183: in function <...se_edition/db/migrations/enterprise/006_1301_to_1500.lua:152>
	[C]: in function 'xpcall'
	./kong/db/init.lua:595: in function 'run_migrations'
	./kong/cmd/utils/migrations.lua:174: in function <./kong/cmd/utils/migrations.lua:158>
	 ...
	```

	This commit fixes the issue in migration.