feat(rbac/session) hash rbac tokens and add sessions to admin api (#800)
* feat(rbac) hash rbac_user user_token values

bcrypt is introduced to store rbac_user token digest values in the
db. an additional field, 'user_token_ident', is introduced to store
an identifying value (the first 5 characters of the sha1 of the
user_token). range queries are used to grab a list of rbac_user
objects and iterate on bcrypt verification. in the vast majority of
cases, token idents will be unique, as the keyspace for the ident is

16^5 = 2^20 = 1048576

thus the cost to validate a given rbac token is O(1) until several
hundred thousand tokens are present within the table.

this commit does not ship with a migration, as we try to avoid
DML adjustments in migrations. instead, an in-place update to the
token is sent the first time it is encountered.

* hotfix(migrations) move optional super admin creation

the migration that was used to create an initial super-admin
user relied on the DAO. because the previous commit to introduce
rbac_user token hashing introduced a new schema field, this
previously-written migration failed due to misalignment between the
DAO schema expectations and the postgres schema. this commit moves
the optional logic (powered by an environmental variable) to create
an initial rbac_user associated with the default super-admin role,
to a separate migration, run after the DDL migration that adds the
user_token_ident column. prior to this commit, attempts to bootstrap
a cluster with the following:

KONG_PASSWORD=<...> kong migrations up

would fail with:

Error: [postgres error] Error during migration 2018-04-20-122000_rbac_defaults:
[postgres error] ERROR: column "user_token_ident" does not exist (14)

this commit commits the cardinal sin of modifying a preivously-released
migration. the justification for this method is twofold: a) the migration
in question is a DML migration altered ONLY in a destructive format,
and the destroyed portion of the migration is restored with no
functional change following the necessary DDL adjustments to the rbac_user
schema, and b). existing clusters migrated from previous versions
will execute this migration as a nop (due to the early bail if an
existing 'kong-admin' rbac_user row is found).

* feat(session) add sessions to admin api (#761)

* feat(sessions) add sessions to admin api
We are now using encrypted sessions on the admin api using the
kong-plugin-session plugin instead of looking up and attaching
the rbac token header since it is now encrypted in the db.
* feat(sessions) add admin_gui_session_conf
* fix(session) add session to built in plugins
* feat(session) add plugin session as dependency
kong-plugin-session is now a luarock dependency

* feat(rbac) integrate api authenticate to run with cryptic rbac
Now that we have encrypted rbac tokens, we needed to remove the lookup
of the rbac token on the incoming session or credential. If authenticate
attaches an rbac_user onto self, then we can pass that into the
validate_user method to bypass token crypt checks, since we already have
confirmed that this is authentic rbac user via consumer mapping.
* fix(rbac) add user in before_filter so ctx.rbac user is set
* fix(rbac) ensure workspace ctx is being loaded
* add back resolve_ws_scope inside load_rbac_ctx since this is needed
for `entity_relationships` call.

* fix(migration) ensure migrate() has a password to use
* fix(migration) create basic-auth credential if password is set
Now that rbac_users.user_token is encrypted, we must create the
new credential from a plaintext value. The only place we have
that is in the KONG_PASSWORD environment variable.

* tests(*) reference raw user tokens for admin api auth
* tests(admin) admin remove user header
* tests(admin) refactor to not rely on db calls
* tests(session) unit test plugin order execution
* tests(rbac) remove -user header

* docs(conf) rename var to actual directive name

* fix(rbac) error handling retrieving token

* hotfix(rbac) run in-place rbac token hash without workspace ctx

* feat(gui) add rbac user header to kconfig

* fix(admin) authenticate to check whitelist after rbac/auth check

* test(gui) fix kconfig test typo