feat(db) validate migrations with schema
Produces errors such as:

$ kong migrations up
Error: migration 'kong.db.migrations.core.000-base' of 'core' subsystem
is invalid: schema violation (postgres.up: required field missing)