chore(deps) do not pin kong-plugin-session
EE 2.3.2.0 comes by default with lua-resty-session 3.8-1 installed (brand new docker image):

```
[kong-enterprise-edition-2.3.2.0-alpine:/]# luarocks show lua-resty-session
lua-resty-session 3.8-1 - Session Library for OpenResty – Flexible and Secure
```

But the kong-plugin-session 2.4.3 was still using lua-resty-session 3.6-1:

```
[kong-enterprise-edition-2.3.2.0-alpine:/]# luarocks remove lua-resty-session 3.6-1
Checking stability of dependencies in the absence of
lua-resty-session 3.6-1...
Will not remove lua-resty-session 3.6-1.
Removing it would break dependencies for: 
kong-plugin-session 2.4.3-1
Use --force to force removal (warning: this may break modules).
Error: Failed removing.
```

That was because we were pinning kong-plugin-session to 2.4.3.

We should not pin it, instead let luarocks use its "pessimistic" operator to 
pickup the latest 2.4.x minor release of kong-plugin-session.